import { TourStep } from '../components/OnboardingTour';

export const TOUR_STEPS: TourStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to Thryvin!',
    description: "Let's take a quick tour! I'll show you everything in under a minute.",
    placement: 'center',
    action: 'none',
    icon: 'sparkles',
  },
  {
    id: 'home-overview',
    title: 'Your Dashboard',
    description: 'This is Home. Your activity rings track daily movement, and your AI-generated workout is ready to go.',
    placement: 'center',
    action: 'none',
    icon: 'home',
    tab: 'index',
  },
  {
    id: 'workouts-overview',
    title: 'Your Training Week',
    description: "Here's your full weekly plan. Each day has a unique workout tailored to your goals. Tap any day to see the exercises.",
    placement: 'center',
    action: 'none',
    icon: 'calendar',
    tab: 'workouts',
  },
  {
    id: 'workout-start',
    title: 'Starting a Workout',
    description: "Hit 'Begin Workout' and you'll see exercise videos showing proper form, plus input fields to log your sets, reps, and weight.",
    placement: 'center',
    action: 'none',
    icon: 'play-circle',
    tab: 'workouts',
  },
  {
    id: 'stats-overview',
    title: 'Track Your Progress',
    description: 'Stats shows your personal records, strength trends, and workout history. Watch yourself get stronger over time.',
    placement: 'center',
    action: 'none',
    icon: 'stats-chart',
    tab: 'stats',
  },
  {
    id: 'awards-overview',
    title: 'Earn Achievements',
    description: 'Complete workouts, hit PRs, and build streaks to unlock badges. Collect them all to progress to new islands!',
    placement: 'center',
    action: 'none',
    icon: 'trophy',
    tab: 'awards',
  },
  {
    id: 'profile-overview',
    title: 'Your Profile',
    description: 'Manage your account, adjust workout preferences, view your subscription, and access settings here.',
    placement: 'center',
    action: 'none',
    icon: 'person-circle',
    tab: 'profile',
  },
  {
    id: 'complete',
    title: "You're All Set!",
    description: "That's the tour! Head back to Home and start today's workout. Your AI coach is always a tap away.",
    placement: 'center',
    action: 'none',
    icon: 'checkmark-circle',
    tab: 'index',
  },
];
