import { TourStep } from '../components/OnboardingTour';

export const TOUR_STEPS: TourStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to Thryvin',
    description: 'Your AI-powered fitness coach. Let me show you around.',
    placement: 'center',
    icon: 'sparkles',
    tab: 'index',
  },
  {
    id: 'home_workout',
    title: "Today's Workout",
    description: 'Your AI builds a personalised plan for each day. Tap to start your session.',
    placement: 'bottom',
    icon: 'barbell',
    tab: 'index',
  },
  {
    id: 'progress_rings',
    title: 'Progress Rings',
    description: 'Track calories, minutes and workout streaks at a glance.',
    placement: 'bottom',
    icon: 'analytics',
    tab: 'index',
  },
  {
    id: 'workouts_tab',
    title: 'Your Plan',
    description: 'View your full 3-week schedule, explore exercises and swap workouts.',
    placement: 'center',
    icon: 'calendar',
    tab: 'workouts',
  },
  {
    id: 'explore_exercises',
    title: 'Explore Exercises',
    description: 'Browse video demos, like your favourites and filter by muscle or equipment.',
    placement: 'center',
    icon: 'search',
    tab: 'workouts',
  },
  {
    id: 'awards_tab',
    title: 'Awards & Badges',
    description: 'Earn badges as you train. Complete islands to unlock new achievements.',
    placement: 'center',
    icon: 'trophy',
    tab: 'awards',
  },
  {
    id: 'coach_chat',
    title: 'AI Coach',
    description: 'Tap the coach bubble anytime for form tips, motivation, or to ask anything.',
    placement: 'center',
    icon: 'chatbubble-ellipses',
    tab: 'index',
  },
  {
    id: 'start_workout_tip',
    title: 'Start Your Workout',
    description: "When you begin, you'll see exercise videos and can log every set. Let's go!",
    placement: 'center',
    action: 'tap',
    icon: 'play-circle',
    tab: 'index',
  },
  {
    id: 'done',
    title: "You're All Set!",
    description: "That's the tour. You can replay it anytime from your profile.",
    placement: 'center',
    icon: 'checkmark-circle',
    tab: 'index',
  },
];
