import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Modal,
  TouchableOpacity,
  ScrollView,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';

const COLORS = {
  accent: '#A22BF6',
  white: '#ffffff',
  text: '#222222',
  lightGray: '#F8F9FA',
  mediumGray: '#8E8E93',
};

interface LegalModalProps {
  visible: boolean;
  onClose: () => void;
  type: 'privacy' | 'terms';
}

const PRIVACY_POLICY = `Privacy Policy – Thryvin

Last updated: December 2024

Thryvin ("we", "our", or "us") respects your privacy and is committed to protecting your personal data. This Privacy Policy explains what information we collect, how we use it, and your rights when using the Thryvin app.


1. INFORMATION WE COLLECT

We collect information you provide directly when you create an account and use the app, including:

Account Information
• Name
• Email address
• Password (stored securely in encrypted/hashed form)

Personal & Fitness Information
• Age
• Height and weight
• Fitness goals and preferences
• Injury information (provided by you)
• Training history, workouts completed, and progress data

Injury information is used only to tailor workouts and avoid recommending exercises that may aggravate existing injuries. Thryvin does not provide medical diagnosis or injury treatment advice.

App Usage Information
• Interactions with the app and AI coach
• Feature usage and basic analytics to improve performance and reliability


2. HOW WE USE YOUR INFORMATION

We use your information to:
• Create and manage your account
• Provide personalised fitness guidance and workout plans
• Adapt training recommendations based on your goals, preferences, and injuries
• Improve app functionality and user experience
• Communicate important account or service-related information

We do not sell your personal data.


3. AI PROCESSING

Thryvin uses artificial intelligence to generate personalised fitness guidance based on the information you provide. Some user inputs may be processed by third-party AI service providers strictly for the purpose of generating responses.

AI-generated content is intended for general fitness guidance only and should not be considered medical advice.


4. PAYMENTS

If you choose to subscribe to paid features in the future:
• Payments are processed by third-party payment providers (such as Apple, Google, or Stripe)
• We do not store or have access to your full payment or banking details
• Payment providers process your data according to their own privacy policies


5. DATA STORAGE & SECURITY

We take reasonable technical and organisational measures to protect your data, including secure storage and encryption where appropriate. However, no system is completely secure, and we cannot guarantee absolute security.


6. DATA RETENTION

We retain your personal data only for as long as necessary to:
• Provide the service
• Comply with legal obligations
• Resolve disputes and enforce agreements

You may request deletion of your account and associated data at any time.


7. YOUR RIGHTS (UK/EU USERS)

You have the right to:
• Access your personal data
• Request correction of inaccurate data
• Request deletion of your data
• Withdraw consent where applicable

To exercise these rights, contact us at:
support@thryvin.app


8. CHILDREN'S PRIVACY

Thryvin is not intended for use by individuals under the age of 16. We do not knowingly collect personal data from children.


9. CHANGES TO THIS POLICY

We may update this Privacy Policy from time to time. Any changes will be posted on this page, and continued use of the app constitutes acceptance of the updated policy.


10. CONTACT US

If you have any questions about this Privacy Policy or how your data is handled, contact:
Email: support@thryvin.app`;

const TERMS_OF_SERVICE = `Terms and Conditions – Thryvin

Last updated: December 2024

These Terms and Conditions ("Terms") govern your use of the Thryvin mobile application ("Thryvin", "the App", "we", "our", or "us"). By creating an account or using the App, you agree to these Terms.

If you do not agree, you must not use the App.


1. PURPOSE OF THE APP

Thryvin provides general fitness guidance, workout planning, and motivational support using AI-powered tools. The App is designed to help users stay consistent with training and improve overall fitness.

Thryvin is not a medical service and does not provide medical, diagnostic, or rehabilitation advice.


2. FITNESS & MEDICAL DISCLAIMER

You acknowledge and agree that:
• All fitness guidance provided is for general informational purposes only
• You may wish to consult a qualified healthcare professional before starting any exercise program
• Thryvin does not diagnose, treat, or prevent injuries or medical conditions

You use the App at your own risk.


3. AI-GENERATED CONTENT

Some content within Thryvin is generated by artificial intelligence.

You acknowledge that:
• AI-generated responses may not always be accurate or complete
• You remain responsible for deciding how to act on the information provided
• AI guidance does not replace professional advice


4. USER ACCOUNTS

To use Thryvin, you must create an account.

You agree to:
• Provide accurate and truthful information
• Keep your login details secure
• Notify us of any unauthorised account use

You are responsible for all activity that occurs under your account.

You must be at least 16 years old to use Thryvin.


5. USER RESPONSIBILITIES

You agree not to:
• Use the App for unlawful purposes
• Misuse, abuse, or attempt to exploit the App or its systems
• Provide false or misleading information
• Attempt to reverse engineer or disrupt the App

We reserve the right to restrict or terminate access if these Terms are violated.


6. INJURIES & LIMITATIONS

If you provide information about injuries or physical limitations:
• Thryvin will attempt to avoid recommending exercises that may worsen those injuries
• This does not guarantee injury prevention
• You remain responsible for listening to your body and stopping if pain or discomfort occurs


7. SUBSCRIPTIONS & PAYMENTS

Thryvin may offer free and paid subscription plans.

If you purchase a subscription:
• Payments are processed by Apple App Store or Google Play
• Pricing, billing frequency, and renewal terms are shown at purchase
• You can manage or cancel subscriptions through your app store account

We do not control app store billing systems.


8. NO GUARANTEES

We do not guarantee:
• Specific fitness results
• Continuous availability of the App
• Error-free or uninterrupted service

Results vary between individuals.


9. INTELLECTUAL PROPERTY

All content, features, designs, text, graphics, and software within Thryvin are owned by or licensed to us.

You may not copy, modify, distribute, or exploit any part of the App without permission.


10. TERMINATION

We may suspend or terminate your account:
• If you violate these Terms
• If required by law
• To protect the integrity of the App

You may stop using the App at any time.


11. LIMITATION OF LIABILITY

To the maximum extent permitted by law:
• Thryvin is not liable for injuries, losses, or damages resulting from use of the App
• Use of the App is entirely at your own risk

Nothing in these Terms limits liability that cannot legally be excluded.


12. CHANGES TO THESE TERMS

We may update these Terms from time to time. Continued use of the App after changes means you accept the updated Terms.


13. GOVERNING LAW

These Terms are governed by the laws of the United Kingdom.


14. CONTACT

If you have questions about these Terms, contact:
Email: support@thryvin.app`;

export const LegalModal = ({ visible, onClose, type }: LegalModalProps) => {
  const isPrivacy = type === 'privacy';
  const content = isPrivacy ? PRIVACY_POLICY : TERMS_OF_SERVICE;
  const title = isPrivacy ? 'Privacy Policy' : 'Terms of Service';

  return (
    <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}>
      <View style={styles.overlay}>
        <View style={styles.container}>
          {/* Header */}
          <View style={styles.header}>
            <TouchableOpacity onPress={onClose} style={styles.closeButton}>
              <Ionicons name="close" size={24} color={COLORS.mediumGray} />
            </TouchableOpacity>
            <Text style={styles.title}>{title}</Text>
            <View style={{ width: 32 }} />
          </View>

          {/* Icon */}
          <View style={styles.iconContainer}>
            <Ionicons 
              name={isPrivacy ? 'shield-checkmark' : 'document-text'} 
              size={40} 
              color={COLORS.accent} 
            />
          </View>

          <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
            <Text style={styles.contentText}>{content}</Text>
            <View style={{ height: 40 }} />
          </ScrollView>

          {/* Accept Button */}
          <View style={styles.footer}>
            <TouchableOpacity style={styles.acceptButton} onPress={onClose}>
              <Text style={styles.acceptButtonText}>I Understand</Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  container: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '90%',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGray,
  },
  closeButton: {
    padding: 4,
  },
  title: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.text,
  },
  iconContainer: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  content: {
    paddingHorizontal: 20,
  },
  contentText: {
    fontSize: 14,
    color: COLORS.text,
    lineHeight: 22,
  },
  footer: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: COLORS.lightGray,
  },
  acceptButton: {
    backgroundColor: COLORS.accent,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  acceptButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.white,
  },
});
